v.shchuka/homework_lesson_1
desfarik/it-academy-FD1-202-22 pull request #14
Opened 2022-10-14 18:26 UTC by Shchuka-Vladimir

2022-10-15 15:56 UTC, Shchuka-Vladimir commented
Хотел изменить описание комита,  я так понял что тут нельзя этого сделать

2022-10-17 13:23 UTC, desfarik requested changes
Лучше переименовать папку и сделать отдельную для дз и лекций. т.е. homework/homework_1 и т.д.

2022-10-17 18:37 UTC, Shchuka-Vladimir commented
Ничего страшного, что я добавил задание с урока в этой ветке?

2022-10-18 12:45 UTC, desfarik commented
> Ничего страшного, что я добавил задание с лекции в этой ветке?

ничего

2022-10-18 12:45 UTC, desfarik approved these changes

2022-10-18 12:49 UTC, merged