homework_1
desfarik/it-academy-FD1-202-22 pull request #36
Opened 2022-10-16 19:55 UTC by OlegPlavskkiy

2022-10-17 14:13 UTC, desfarik reviewed
Нужно создать папку для дз!

2022-10-17 14:14 UTC, desfarik commented on src/o.plavskiy/task2.html
> +        <p><a href="file:///C:/Users/%D0%9E%D0%BB%D0%B5%D0%B3/Desktop/IT/HW1/Task2/Test-paragraphs.html/#50">&#167 50</a></p>
Это абсолютная ссылка, которая работать не будет!

2022-10-17 14:19 UTC, desfarik requested changes
Папка для ДЗ -> мерж

2022-10-17 14:35 UTC, OlegPlavskkiy commented
> Папка для ДЗ -> мерж

Эту папку мне нужно создать в папке o.plavskiy, которую я добавил в src ?

2022-10-18 08:59 UTC, desfarik commented
> > Папка для ДЗ -> мерж
> 
> Эту папку мне нужно создать в папке o.plavskiy, которую я добавил в src ?

Да!

2022-10-21 09:05 UTC, desfarik approved these changes

2022-10-21 09:11 UTC, merged